<ENVELOPE>
 <HEADER>
  <TALLYREQUEST>Import Data</TALLYREQUEST>
 </HEADER>
 <BODY>
  <IMPORTDATA>
   <REQUESTDESC>
    <REPORTNAME>Vouchers</REPORTNAME>
    <STATICVARIABLES>
     <SVCURRENTCOMPANY>{{$company_details['company_name']}}</SVCURRENTCOMPANY>
    </STATICVARIABLES>
   </REQUESTDESC>
   <REQUESTDATA>
    <TALLYMESSAGE xmlns:UDF="TallyUDF">
     <VOUCHER REMOTEID="b46bc1ff-4e17-4958-adfa-6b8b0b8dde8e-00001d72" VCHKEY="b46bc1ff-4e17-4958-adfa-6b8b0b8dde8e-0000a8e3:00000040" VCHTYPE="Purchase Order" ACTION="Create" OBJVIEW="Invoice Voucher View">
      <ADDRESS.LIST TYPE="String">
       <ADDRESS>{{$supplier_shipping_add_details['address']}}</ADDRESS>
       <ADDRESS>Pin: {{$supplier_shipping_add_details['pincode']}}</ADDRESS>
      </ADDRESS.LIST>
      <BASICBUYERADDRESS.LIST TYPE="String">
       <BASICBUYERADDRESS>{{$company_shipping_add_details['address']}}</BASICBUYERADDRESS>
       <BASICBUYERADDRESS>{{$company_city_name['title']}} {{$company_shipping_add_details['pincode']}}</BASICBUYERADDRESS>
       <BASICBUYERADDRESS>Contact Person: {{$company_details['shipping_name']}}- {{$company_details['shipping_phone']}}</BASICBUYERADDRESS>
       <BASICBUYERADDRESS>Tel No.: {{$company_details['spoc_phone']}}</BASICBUYERADDRESS>
       <BASICBUYERADDRESS>E-Mail : {{$company_details['spoc_email']}}</BASICBUYERADDRESS>
      </BASICBUYERADDRESS.LIST>
      <BASICORDERTERMS.LIST TYPE="String">
       <BASICORDERTERMS>{{$company_details['shipping_phone']}}</BASICORDERTERMS>
      </BASICORDERTERMS.LIST>
      <OLDAUDITENTRYIDS.LIST TYPE="Number">
       <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
      </OLDAUDITENTRYIDS.LIST>
      <DATE>{{$current_date}}</DATE>
      <GUID>b46bc1ff-4e17-4958-adfa-6b8b0b8dde8e-00001d72</GUID>
      <STATENAME>{{$supplier_state_name['title']}}</STATENAME>
      <COUNTRYOFRESIDENCE>{{$supplier_country_name['title']}}</COUNTRYOFRESIDENCE>
      <PARTYGSTIN>{{$supplier_details['gst_no']}}</PARTYGSTIN>
      <PARTYNAME>{{$supplier_details['supplier_name']}}</PARTYNAME>
      <VOUCHERTYPENAME>Purchase Order</VOUCHERTYPENAME>
      <REFERENCE>{{$tally_data['po_no']}}</REFERENCE>
      <VOUCHERNUMBER>{{$tally_data['po_no']}}</VOUCHERNUMBER>
      <PARTYLEDGERNAME>{{$supplier_state_name['supplier_name']}}</PARTYLEDGERNAME>
      <BASICBASEPARTYNAME>{{$supplier_state_name['supplier_name']}}</BASICBASEPARTYNAME>
      <CSTFORMISSUETYPE/>
      <CSTFORMRECVTYPE/>
      <FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>
      <PERSISTEDVIEW>Invoice Voucher View</PERSISTEDVIEW>
      <PLACEOFSUPPLY>{{$supplier_state_name['title']}}</PLACEOFSUPPLY>
      <CONSIGNEEGSTIN>{{$company_details['gst_no']}}</CONSIGNEEGSTIN>
      <BASICSHIPPEDBY>Courier</BASICSHIPPEDBY>
      <BASICBUYERNAME>{{$company_details['company_name']}}</BASICBUYERNAME>
      <BASICFINALDESTINATION>{{$company_city_name['title']}}</BASICFINALDESTINATION>
      <BASICBUYERSSALESTAXNO>260020000281</BASICBUYERSSALESTAXNO>
      <BASICDUEDATEOFPYMT>60 Days</BASICDUEDATEOFPYMT>
      <BUYERADDRESSTYPE>Delivery Address {{$company_city_name['title']}}</BUYERADDRESSTYPE>
      <VCHGSTCLASS/>
      <CONSIGNEESTATENAME>{{$company_state_name['title']}}</CONSIGNEESTATENAME>
      <DIFFACTUALQTY>No</DIFFACTUALQTY>
      <ISMSTFROMSYNC>No</ISMSTFROMSYNC>
      <ASORIGINAL>No</ASORIGINAL>
      <AUDITED>No</AUDITED>
      <FORJOBCOSTING>No</FORJOBCOSTING>
      <ISOPTIONAL>No</ISOPTIONAL>
      <EFFECTIVEDATE>20180516</EFFECTIVEDATE>
      <USEFOREXCISE>No</USEFOREXCISE>
      <ISFORJOBWORKIN>No</ISFORJOBWORKIN>
      <ALLOWCONSUMPTION>No</ALLOWCONSUMPTION>
      <USEFORINTEREST>No</USEFORINTEREST>
      <USEFORGAINLOSS>No</USEFORGAINLOSS>
      <USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER>
      <USEFORCOMPOUND>No</USEFORCOMPOUND>
      <USEFORSERVICETAX>No</USEFORSERVICETAX>
      <ISEXCISEVOUCHER>No</ISEXCISEVOUCHER>
      <EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE>
      <USEFORTAXUNITTRANSFER>No</USEFORTAXUNITTRANSFER>
      <EXCISEOPENING>No</EXCISEOPENING>
      <USEFORFINALPRODUCTION>No</USEFORFINALPRODUCTION>
      <ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN>
      <ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN>
      <ISTDSTCSCASHVCH>No</ISTDSTCSCASHVCH>
      <INCLUDEADVPYMTVCH>No</INCLUDEADVPYMTVCH>
      <ISSUBWORKSCONTRACT>No</ISSUBWORKSCONTRACT>
      <ISVATOVERRIDDEN>No</ISVATOVERRIDDEN>
      <IGNOREORIGVCHDATE>No</IGNOREORIGVCHDATE>
      <ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN>
      <ISISDVOUCHER>No</ISISDVOUCHER>
      <ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN>
      <ISEXCISESUPPLYVCH>No</ISEXCISESUPPLYVCH>
      <ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN>
      <GSTNOTEXPORTED>No</GSTNOTEXPORTED>
      <ISVATPRINCIPALACCOUNT>No</ISVATPRINCIPALACCOUNT>
      <ISBOENOTAPPLICABLE>No</ISBOENOTAPPLICABLE>
      <ISSHIPPINGWITHINSTATE>No</ISSHIPPINGWITHINSTATE>
      <ISOVERSEASTOURISTTRANS>No</ISOVERSEASTOURISTTRANS>
      <ISCANCELLED>No</ISCANCELLED>
      <HASCASHFLOW>No</HASCASHFLOW>
      <ISPOSTDATED>No</ISPOSTDATED>
      <USETRACKINGNUMBER>No</USETRACKINGNUMBER>
      <ISINVOICE>No</ISINVOICE>
      <MFGJOURNAL>No</MFGJOURNAL>
      <HASDISCOUNTS>No</HASDISCOUNTS>
      <ASPAYSLIP>No</ASPAYSLIP>
      <ISCOSTCENTRE>No</ISCOSTCENTRE>
      <ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH>
      <ISEXCISEMANUFACTURERON>No</ISEXCISEMANUFACTURERON>
      <ISBLANKCHEQUE>No</ISBLANKCHEQUE>
      <ISVOID>No</ISVOID>
      <ISONHOLD>No</ISONHOLD>
      <ORDERLINESTATUS>No</ORDERLINESTATUS>
      <VATISAGNSTCANCSALES>No</VATISAGNSTCANCSALES>
      <VATISPURCEXEMPTED>No</VATISPURCEXEMPTED>
      <ISVATRESTAXINVOICE>No</ISVATRESTAXINVOICE>
      <VATISASSESABLECALCVCH>No</VATISASSESABLECALCVCH>
      <ISVATDUTYPAID>Yes</ISVATDUTYPAID>
      <ISDELIVERYSAMEASCONSIGNEE>No</ISDELIVERYSAMEASCONSIGNEE>
      <ISDISPATCHSAMEASCONSIGNOR>No</ISDISPATCHSAMEASCONSIGNOR>
      <ISDELETED>No</ISDELETED>
      <CHANGEVCHMODE>No</CHANGEVCHMODE>
      <ALTERID> 14386</ALTERID>
      <MASTERID> 7538</MASTERID>
      <VOUCHERKEY>185692911042624</VOUCHERKEY>
      <EXCLUDEDTAXATIONS.LIST>      </EXCLUDEDTAXATIONS.LIST>
      <OLDAUDITENTRIES.LIST>      </OLDAUDITENTRIES.LIST>
      <ACCOUNTAUDITENTRIES.LIST>      </ACCOUNTAUDITENTRIES.LIST>
      <AUDITENTRIES.LIST>      </AUDITENTRIES.LIST>
      <DUTYHEADDETAILS.LIST>      </DUTYHEADDETAILS.LIST>
      <SUPPLEMENTARYDUTYHEADDETAILS.LIST>      </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
      <INVOICEDELNOTES.LIST>      </INVOICEDELNOTES.LIST>
      <INVOICEORDERLIST.LIST>      </INVOICEORDERLIST.LIST>
      <INVOICEINDENTLIST.LIST>      </INVOICEINDENTLIST.LIST>
      <ATTENDANCEENTRIES.LIST>      </ATTENDANCEENTRIES.LIST>
      <ORIGINVOICEDETAILS.LIST>      </ORIGINVOICEDETAILS.LIST>
      <INVOICEEXPORTLIST.LIST>      </INVOICEEXPORTLIST.LIST>
      <LEDGERENTRIES.LIST>
       <OLDAUDITENTRYIDS.LIST TYPE="Number">
        <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
       </OLDAUDITENTRYIDS.LIST>
       <LEDGERNAME>{{$supplier_details['supplier_name']}}</LEDGERNAME>
       <GSTCLASS/>
       <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
       <LEDGERFROMITEM>No</LEDGERFROMITEM>
       <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
       <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
       <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
       <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
       <AMOUNT>{{$total_price_tax}}</AMOUNT>
       <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
       <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
       <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>
       <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
       <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
       <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
       <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
       <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
       <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
       <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
       <RATEDETAILS.LIST>       </RATEDETAILS.LIST>
       <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
       <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
       <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
       <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
       <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
       <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
       <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
       <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>
       <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
       <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
       <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
       <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
      </LEDGERENTRIES.LIST>
      <LEDGERENTRIES.LIST>
       @if($company_state_name['title'] != $supplier_state_name['title'])
       <OLDAUDITENTRYIDS.LIST TYPE="Number">
        <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
       </OLDAUDITENTRYIDS.LIST>
       <ROUNDTYPE>Normal Rounding</ROUNDTYPE>
        <LEDGERNAME>Integrated Tax (IGST)</LEDGERNAME>
       <GSTCLASS/>
       <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
       <LEDGERFROMITEM>No</LEDGERFROMITEM>
       <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
       <ISPARTYLEDGER>No</ISPARTYLEDGER>
       <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
       <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
       <ROUNDLIMIT> 1</ROUNDLIMIT>
       <AMOUNT>{{$total_tax}}</AMOUNT>
       <VATEXPAMOUNT>{{$total_tax}}</VATEXPAMOUNT>
       <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
       <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
       <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>
       <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
       <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
       <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
       <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
       <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
       <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
       <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
       <RATEDETAILS.LIST>       </RATEDETAILS.LIST>
       <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
       <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
       <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
       <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
       <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
       <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
       <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
       <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>
       <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
       <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
       <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
       <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
      </LEDGERENTRIES.LIST>
      @else
        <OLDAUDITENTRYIDS.LIST TYPE="Number">
        <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
       </OLDAUDITENTRYIDS.LIST>
       <ROUNDTYPE>Normal Rounding</ROUNDTYPE>
        <LEDGERNAME>State Tax(SGST)</LEDGERNAME>
       <GSTCLASS/>
       <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
       <LEDGERFROMITEM>No</LEDGERFROMITEM>
       <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
       <ISPARTYLEDGER>No</ISPARTYLEDGER>
       <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
       <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
       <ROUNDLIMIT> 1</ROUNDLIMIT>
       <AMOUNT>{{$total_tax}}</AMOUNT>
       <VATEXPAMOUNT>{{$total_tax}}</VATEXPAMOUNT>
       <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
       <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
       <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>
       <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
       <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
       <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
       <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
       <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
       <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
       <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
       <RATEDETAILS.LIST>       </RATEDETAILS.LIST>
       <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
       <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
       <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
       <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
       <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
       <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
       <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
       <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>
       <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
       <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
       <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
       <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
      </LEDGERENTRIES.LIST>
      <LEDGERENTRIES.LIST>
      <OLDAUDITENTRYIDS.LIST TYPE="Number">
        <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
       </OLDAUDITENTRYIDS.LIST>
       <ROUNDTYPE>Normal Rounding</ROUNDTYPE>
        <LEDGERNAME>Central Tax (CGST)</LEDGERNAME>
       <GSTCLASS/>
       <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
       <LEDGERFROMITEM>No</LEDGERFROMITEM>
       <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
       <ISPARTYLEDGER>No</ISPARTYLEDGER>
       <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
       <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
       <ROUNDLIMIT> 1</ROUNDLIMIT>
       <AMOUNT>{{$total_tax}}</AMOUNT>
       <VATEXPAMOUNT>{{$total_tax}}</VATEXPAMOUNT>
       <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
       <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
       <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>
       <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
       <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
       <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
       <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
       <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
       <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
       <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
       <RATEDETAILS.LIST>       </RATEDETAILS.LIST>
       <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
       <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
       <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
       <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
       <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
       <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
       <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
       <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>
       <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
       <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
       <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
       <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
      </LEDGERENTRIES.LIST>
      @endif
      @foreach($get_model_details as $key=>$value)
        @foreach($value as $key1=>$value1)
          <ALLINVENTORYENTRIES.LIST>
           <BASICUSERDESCRIPTION.LIST TYPE="String">
            <BASICUSERDESCRIPTION>6&quot; VAV Box</BASICUSERDESCRIPTION>
            <BASICUSERDESCRIPTION>{{$value1['product_name']}}</BASICUSERDESCRIPTION>
           </BASICUSERDESCRIPTION.LIST>
           <STOCKITEMNAME>{{$value1['model_no']}}</STOCKITEMNAME>
           <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
           <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
           <ISAUTONEGATE>No</ISAUTONEGATE>
           <ISCUSTOMSCLEARANCE>No</ISCUSTOMSCLEARANCE>
           <ISTRACKCOMPONENT>No</ISTRACKCOMPONENT>
           <ISTRACKPRODUCTION>No</ISTRACKPRODUCTION>
           <ISPRIMARYITEM>No</ISPRIMARYITEM>
           <ISSCRAP>No</ISSCRAP>
           @if($tally_data['currency_status'] == 'rupee')
             <RATE>{{$value1['unit_price']}}/Nos</RATE>
             <AMOUNT>{{$value1['total_price']}}</AMOUNT>
            @elseif($tally_data['currency_status'] == 'dollar')
              <RATE>{{$value1['dollar_price']}}/Nos</RATE>
             <AMOUNT>{{$value1['dollar_price'] * $value1['qty']}}</AMOUNT>
            @endif
           <ACTUALQTY> {{$value1['qty']}} Nos</ACTUALQTY>
           <BILLEDQTY> {{$value1['qty']}} Nos</BILLEDQTY>
           <BATCHALLOCATIONS.LIST>
            <GODOWNNAME>Stellar Ecoenergy Solutions LLP</GODOWNNAME>
            <BATCHNAME>Primary Batch</BATCHNAME>
            <DESTINATIONGODOWNNAME>{{$company_details['company_name']}}</DESTINATIONGODOWNNAME>
            <INDENTNO/>
            <ORDERNO>{{$value1['po_no']}}</ORDERNO>
            <TRACKINGNUMBER/>
            <DYNAMICCSTISCLEARED>No</DYNAMICCSTISCLEARED>
            @if($tally_data['currency_status'] == 'rupee')
             <AMOUNT>{{$value1['total_price']}}</AMOUNT>
            @elseif($tally_data['currency_status'] == 'dollar')
             <AMOUNT>{{$value1['dollar_price'] * $value1['qty']}}</AMOUNT>
            @endif
            <ACTUALQTY> {{$value1['qty']}} Nos</ACTUALQTY>
            <BILLEDQTY> {{$value1['qty']}} Nos</BILLEDQTY>
            <ORDERDUEDATE JD="43235" P="16-May-2018">{{$date_format}}</ORDERDUEDATE>
            <ADDITIONALDETAILS.LIST>        </ADDITIONALDETAILS.LIST>
            <VOUCHERCOMPONENTLIST.LIST>        </VOUCHERCOMPONENTLIST.LIST>
           </BATCHALLOCATIONS.LIST>
           <ACCOUNTINGALLOCATIONS.LIST>
            <OLDAUDITENTRYIDS.LIST TYPE="Number">
             <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
            </OLDAUDITENTRYIDS.LIST>
            <LEDGERNAME>Purchase @ GST</LEDGERNAME>
            <GSTCLASS/>
            <GSTOVRDNNATURE>Interstate Purchase Taxable</GSTOVRDNNATURE>
            <GSTOVRDNINELIGIBLEITC> Not Applicable</GSTOVRDNINELIGIBLEITC>
            <GSTOVRDNISREVCHARGEAPPL> Not Applicable</GSTOVRDNISREVCHARGEAPPL>
            <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
            <LEDGERFROMITEM>No</LEDGERFROMITEM>
            <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
            <ISPARTYLEDGER>No</ISPARTYLEDGER>
            <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
            <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>@if($tally_data['currency_status'] == 'rupee')
             <AMOUNT>{{$value1['total_price']}}</AMOUNT>
            <GSTOVRDNASSESSABLEVALUE>{{$value1['total_price']}}</GSTOVRDNASSESSABLEVALUE>
            @elseif($tally_data['currency_status'] == 'dollar')
             <AMOUNT>{{$value1['dollar_price'] * $value1['qty']}}</AMOUNT>
            <GSTOVRDNASSESSABLEVALUE>-{{$value1['dollar_price'] * $value1['qty']}}</GSTOVRDNASSESSABLEVALUE>
            @endif
            <SERVICETAXDETAILS.LIST>        </SERVICETAXDETAILS.LIST>
            <BANKALLOCATIONS.LIST>        </BANKALLOCATIONS.LIST>
            <BILLALLOCATIONS.LIST>        </BILLALLOCATIONS.LIST>
            <INTERESTCOLLECTION.LIST>        </INTERESTCOLLECTION.LIST>
            <OLDAUDITENTRIES.LIST>        </OLDAUDITENTRIES.LIST>
            <ACCOUNTAUDITENTRIES.LIST>        </ACCOUNTAUDITENTRIES.LIST>
            <AUDITENTRIES.LIST>        </AUDITENTRIES.LIST>
            <INPUTCRALLOCS.LIST>        </INPUTCRALLOCS.LIST>
            <DUTYHEADDETAILS.LIST>        </DUTYHEADDETAILS.LIST>
            <EXCISEDUTYHEADDETAILS.LIST>        </EXCISEDUTYHEADDETAILS.LIST>
            <RATEDETAILS.LIST>
             <GSTRATEDUTYHEAD>Integrated Tax</GSTRATEDUTYHEAD>
            </RATEDETAILS.LIST>
            <RATEDETAILS.LIST>
             <GSTRATEDUTYHEAD>Central Tax</GSTRATEDUTYHEAD>
            </RATEDETAILS.LIST>
            <RATEDETAILS.LIST>
             <GSTRATEDUTYHEAD>State Tax</GSTRATEDUTYHEAD>
            </RATEDETAILS.LIST>
            <RATEDETAILS.LIST>
             <GSTRATEDUTYHEAD>Cess</GSTRATEDUTYHEAD>
            </RATEDETAILS.LIST>
            <SUMMARYALLOCS.LIST>        </SUMMARYALLOCS.LIST>
            <STPYMTDETAILS.LIST>        </STPYMTDETAILS.LIST>
            <EXCISEPAYMENTALLOCATIONS.LIST>        </EXCISEPAYMENTALLOCATIONS.LIST>
            <TAXBILLALLOCATIONS.LIST>        </TAXBILLALLOCATIONS.LIST>
            <TAXOBJECTALLOCATIONS.LIST>        </TAXOBJECTALLOCATIONS.LIST>
            <TDSEXPENSEALLOCATIONS.LIST>        </TDSEXPENSEALLOCATIONS.LIST>
            <VATSTATUTORYDETAILS.LIST>        </VATSTATUTORYDETAILS.LIST>
            <COSTTRACKALLOCATIONS.LIST>        </COSTTRACKALLOCATIONS.LIST>
            <REFVOUCHERDETAILS.LIST>        </REFVOUCHERDETAILS.LIST>
            <INVOICEWISEDETAILS.LIST>        </INVOICEWISEDETAILS.LIST>
            <VATITCDETAILS.LIST>        </VATITCDETAILS.LIST>
            <ADVANCETAXDETAILS.LIST>        </ADVANCETAXDETAILS.LIST>
           </ACCOUNTINGALLOCATIONS.LIST>
           <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
           <SUPPLEMENTARYDUTYHEADDETAILS.LIST>       </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
           <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
           <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
           <EXCISEALLOCATIONS.LIST>       </EXCISEALLOCATIONS.LIST>
           <EXPENSEALLOCATIONS.LIST>       </EXPENSEALLOCATIONS.LIST>
          </ALLINVENTORYENTRIES.LIST>
        @endforeach
      @endforeach
      
      <PAYROLLMODEOFPAYMENT.LIST>      </PAYROLLMODEOFPAYMENT.LIST>
      <ATTDRECORDS.LIST>      </ATTDRECORDS.LIST>
      <TEMPGSTRATEDETAILS.LIST>      </TEMPGSTRATEDETAILS.LIST>
      <UDF:TRADERCONSVATTINNO.LIST DESC="`TraderConsVATTINNo`" ISLIST="YES" TYPE="String" INDEX="10015">
       <UDF:TRADERCONSVATTINNO DESC="`TraderConsVATTINNo`">27091170446V Dt 3.3.2016</UDF:TRADERCONSVATTINNO>
      </UDF:TRADERCONSVATTINNO.LIST>
      <UDF:VATDEALERNATURE.LIST DESC="`VATDealerNature`" ISLIST="YES" TYPE="String" INDEX="10031">
       <UDF:VATDEALERNATURE DESC="`VATDealerNature`">Inter State Dealer</UDF:VATDEALERNATURE>
      </UDF:VATDEALERNATURE.LIST>
     </VOUCHER>
    </TALLYMESSAGE>
    <TALLYMESSAGE xmlns:UDF="TallyUDF">
     <COMPANY>
      <REMOTECMPINFO.LIST MERGE="Yes">
       <NAME>b46bc1ff-4e17-4958-adfa-6b8b0b8dde8e</NAME>
       <REMOTECMPNAME>{{$company_details['company_name']}}</REMOTECMPNAME>
       <REMOTECMPSTATE>{{$company_state_name['title']}}</REMOTECMPSTATE>
      </REMOTECMPINFO.LIST>
     </COMPANY>
    </TALLYMESSAGE>
    <TALLYMESSAGE xmlns:UDF="TallyUDF">
     <COMPANY>
      <REMOTECMPINFO.LIST MERGE="Yes">
       <NAME>b46bc1ff-4e17-4958-adfa-6b8b0b8dde8e</NAME>
       <REMOTECMPNAME>{{$company_details['company_name']}}</REMOTECMPNAME>
       <REMOTECMPSTATE>{{$company_state_name['title']}}</REMOTECMPSTATE>
      </REMOTECMPINFO.LIST>
     </COMPANY>
    </TALLYMESSAGE>
   </REQUESTDATA>
  </IMPORTDATA>
 </BODY>
</ENVELOPE>
