<ENVELOPE>
 <HEADER>
  <TALLYREQUEST>Import Data</TALLYREQUEST>
 </HEADER>
 <BODY>
  <IMPORTDATA>
   <REQUESTDESC>
    <REPORTNAME>Vouchers</REPORTNAME>
    <STATICVARIABLES>
     <SVCURRENTCOMPANY>{{$sales_data['company_name']}}</SVCURRENTCOMPANY>
    </STATICVARIABLES>
   </REQUESTDESC>
   <REQUESTDATA>
    <TALLYMESSAGE xmlns:UDF="TallyUDF">
     <VOUCHER REMOTEID="b46bc1ff-4e17-4958-adfa-6b8b0b8dde8e-00001e6d" VCHKEY="b46bc1ff-4e17-4958-adfa-6b8b0b8dde8e-0000a8f4:00000070" VCHTYPE="Sales Order" ACTION="Create" OBJVIEW="Invoice Voucher View">
      <ADDRESS.LIST TYPE="String">
       <ADDRESS>No.906, 1 st Floor, Raj Arcade,</ADDRESS>
       <ADDRESS>5th &apos;A&apos;  Cross, 1 st Block, HRBR Layout</ADDRESS>
       <ADDRESS>Bangalore - 560043 &#13;&#10;</ADDRESS>
       <ADDRESS>kind Attn - Mr. unni 		9740488141	</ADDRESS>
      </ADDRESS.LIST>
      <BASICBUYERADDRESS.LIST TYPE="String">
       <BASICBUYERADDRESS>M/s Brigade Enterprises Ltd</BASICBUYERADDRESS>
       <BASICBUYERADDRESS>29th floor , world Trade centre , Brigade gateway campus ,</BASICBUYERADDRESS>
       <BASICBUYERADDRESS>26/1, Dr. Raj kumar road , Malleswaram -Rajajinagar</BASICBUYERADDRESS>
       <BASICBUYERADDRESS>Bangalore -560055			</BASICBUYERADDRESS>
       <BASICBUYERADDRESS>kind Attn - Mr.Arun 		9741372770	</BASICBUYERADDRESS>
      </BASICBUYERADDRESS.LIST>
      <BASICORDERTERMS.LIST TYPE="String">
       <BASICORDERTERMS>Immediate</BASICORDERTERMS>
      </BASICORDERTERMS.LIST>
      <OLDAUDITENTRYIDS.LIST TYPE="Number">
       <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
      </OLDAUDITENTRYIDS.LIST>
      <DATE>20180602</DATE>
      <STATENAME>{{$sales_data['state_name']}}</STATENAME>
      <GSTREGISTRATIONTYPE>Regular</GSTREGISTRATIONTYPE>
      <VATDEALERTYPE>Regular</VATDEALERTYPE>
      <COUNTRYOFRESIDENCE>{{$sales_data['country_name']}}</COUNTRYOFRESIDENCE>
      <PARTYGSTIN>{{$sales_data['customer_gst_no']}}</PARTYGSTIN>
      <PARTYNAME>Suraj Mani Engineers Pvt. Ltd</PARTYNAME>
      <VOUCHERTYPENAME>Sales Order</VOUCHERTYPENAME>
      <REFERENCE>779-10 &amp; 02-06-2018</REFERENCE>
      <VOUCHERNUMBER>103</VOUCHERNUMBER>
      <PARTYLEDGERNAME>Suraj Mani Engineers Pvt. Ltd.</PARTYLEDGERNAME>
      <BASICBASEPARTYNAME>Suraj Mani Engineers Pvt. Ltd</BASICBASEPARTYNAME>
      <CSTFORMISSUETYPE/>
      <CSTFORMRECVTYPE/>
      <FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>
      <PERSISTEDVIEW>Invoice Voucher View</PERSISTEDVIEW>
      <PLACEOFSUPPLY>{{$sales_data['state_name']}}</PLACEOFSUPPLY>
      <CONSIGNEEGSTIN>{{$sales_data['company_gst_no']}}</CONSIGNEEGSTIN>
      <BASICSHIPPEDBY>Courier</BASICSHIPPEDBY>
      <BASICBUYERNAME>M/s Brigade Enterprises Ltd</BASICBUYERNAME>
      <BASICFINALDESTINATION>Bangalore</BASICFINALDESTINATION>
      <BASICORDERREF>{{$sales_data['so_no']}}</BASICORDERREF>(so no)
      <BASICDUEDATEOFPYMT>60 days form the date of bill &amp; material recived</BASICDUEDATEOFPYMT>
      <BUYERADDRESSTYPE>M/s Brigade Enterprises Ltd 			&#13;&#10;</BUYERADDRESSTYPE>
      <VCHGSTCLASS/>
      <CONSIGNEEPINNUMBER>AAJCS6218E</CONSIGNEEPINNUMBER>
      <CONSIGNEESTATENAME>{{$sales_data['state_name']}}</CONSIGNEESTATENAME>
      <DIFFACTUALQTY>No</DIFFACTUALQTY>
      <ISMSTFROMSYNC>No</ISMSTFROMSYNC>
      <ASORIGINAL>No</ASORIGINAL>
      <AUDITED>No</AUDITED>
      <FORJOBCOSTING>No</FORJOBCOSTING>
      <ISOPTIONAL>No</ISOPTIONAL>
      <EFFECTIVEDATE>20180602</EFFECTIVEDATE>
      <USEFOREXCISE>No</USEFOREXCISE>
      <ISFORJOBWORKIN>No</ISFORJOBWORKIN>
      <ALLOWCONSUMPTION>No</ALLOWCONSUMPTION>
      <USEFORINTEREST>No</USEFORINTEREST>
      <USEFORGAINLOSS>No</USEFORGAINLOSS>
      <USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER>
      <USEFORCOMPOUND>No</USEFORCOMPOUND>
      <USEFORSERVICETAX>No</USEFORSERVICETAX>
      <ISEXCISEVOUCHER>No</ISEXCISEVOUCHER>
      <EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE>
      <USEFORTAXUNITTRANSFER>No</USEFORTAXUNITTRANSFER>
      <EXCISEOPENING>No</EXCISEOPENING>
      <USEFORFINALPRODUCTION>No</USEFORFINALPRODUCTION>
      <ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN>
      <ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN>
      <ISTDSTCSCASHVCH>No</ISTDSTCSCASHVCH>
      <INCLUDEADVPYMTVCH>No</INCLUDEADVPYMTVCH>
      <ISSUBWORKSCONTRACT>No</ISSUBWORKSCONTRACT>
      <ISVATOVERRIDDEN>No</ISVATOVERRIDDEN>
      <IGNOREORIGVCHDATE>No</IGNOREORIGVCHDATE>
      <ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN>
      <ISISDVOUCHER>No</ISISDVOUCHER>
      <ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN>
      <ISEXCISESUPPLYVCH>No</ISEXCISESUPPLYVCH>
      <ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN>
      <GSTNOTEXPORTED>No</GSTNOTEXPORTED>
      <ISVATPRINCIPALACCOUNT>No</ISVATPRINCIPALACCOUNT>
      <ISBOENOTAPPLICABLE>No</ISBOENOTAPPLICABLE>
      <ISSHIPPINGWITHINSTATE>No</ISSHIPPINGWITHINSTATE>
      <ISOVERSEASTOURISTTRANS>No</ISOVERSEASTOURISTTRANS>
      <ISCANCELLED>No</ISCANCELLED>
      <HASCASHFLOW>No</HASCASHFLOW>
      <ISPOSTDATED>No</ISPOSTDATED>
      <USETRACKINGNUMBER>No</USETRACKINGNUMBER>
      <ISINVOICE>No</ISINVOICE>
      <MFGJOURNAL>No</MFGJOURNAL>
      <HASDISCOUNTS>No</HASDISCOUNTS>
      <ASPAYSLIP>No</ASPAYSLIP>
      <ISCOSTCENTRE>No</ISCOSTCENTRE>
      <ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH>
      <ISEXCISEMANUFACTURERON>No</ISEXCISEMANUFACTURERON>
      <ISBLANKCHEQUE>No</ISBLANKCHEQUE>
      <ISVOID>No</ISVOID>
      <ISONHOLD>No</ISONHOLD>
      <ORDERLINESTATUS>No</ORDERLINESTATUS>
      <VATISAGNSTCANCSALES>No</VATISAGNSTCANCSALES>
      <VATISPURCEXEMPTED>No</VATISPURCEXEMPTED>
      <ISVATRESTAXINVOICE>No</ISVATRESTAXINVOICE>
      <VATISASSESABLECALCVCH>No</VATISASSESABLECALCVCH>
      <ISVATDUTYPAID>Yes</ISVATDUTYPAID>
      <ISDELIVERYSAMEASCONSIGNEE>No</ISDELIVERYSAMEASCONSIGNEE>
      <ISDISPATCHSAMEASCONSIGNOR>No</ISDISPATCHSAMEASCONSIGNOR>
      <ISDELETED>No</ISDELETED>
      <CHANGEVCHMODE>No</CHANGEVCHMODE>
      <ALTERID> 14796</ALTERID>
      <MASTERID> 7789</MASTERID>
      <VOUCHERKEY>185765925486704</VOUCHERKEY>
      <EXCLUDEDTAXATIONS.LIST>      </EXCLUDEDTAXATIONS.LIST>
      <OLDAUDITENTRIES.LIST>      </OLDAUDITENTRIES.LIST>
      <ACCOUNTAUDITENTRIES.LIST>      </ACCOUNTAUDITENTRIES.LIST>
      <AUDITENTRIES.LIST>      </AUDITENTRIES.LIST>
      <DUTYHEADDETAILS.LIST>      </DUTYHEADDETAILS.LIST>
      <SUPPLEMENTARYDUTYHEADDETAILS.LIST>      </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
      <INVOICEDELNOTES.LIST>      </INVOICEDELNOTES.LIST>
      <INVOICEORDERLIST.LIST>      </INVOICEORDERLIST.LIST>
      <INVOICEINDENTLIST.LIST>      </INVOICEINDENTLIST.LIST>
      <ATTENDANCEENTRIES.LIST>      </ATTENDANCEENTRIES.LIST>
      <ORIGINVOICEDETAILS.LIST>      </ORIGINVOICEDETAILS.LIST>
      <INVOICEEXPORTLIST.LIST>      </INVOICEEXPORTLIST.LIST>
      <LEDGERENTRIES.LIST>
       <OLDAUDITENTRYIDS.LIST TYPE="Number">
        <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
       </OLDAUDITENTRYIDS.LIST>
       <LEDGERNAME>Suraj Mani Engineers Pvt. Ltd.</LEDGERNAME>
       <GSTCLASS/>
       <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
       <LEDGERFROMITEM>No</LEDGERFROMITEM>
       <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
       <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
       <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
       <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
       <AMOUNT>-188328.00</AMOUNT>
       <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
       <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
       <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>
       <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
       <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
       <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
       <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
       <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
       <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
       <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
       <RATEDETAILS.LIST>       </RATEDETAILS.LIST>
       <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
       <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
       <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
       <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
       <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
       <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
       <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
       <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>
       <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
       <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
       <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
       <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
      </LEDGERENTRIES.LIST>
      <LEDGERENTRIES.LIST>
       <OLDAUDITENTRYIDS.LIST TYPE="Number">
        <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
       </OLDAUDITENTRYIDS.LIST>
       <ROUNDTYPE/>
       <LEDGERNAME>Freight - GST</LEDGERNAME>
       <GSTCLASS/>
       <GSTOVRDNNATURE>Interstate Sales Taxable</GSTOVRDNNATURE>
       <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
       <LEDGERFROMITEM>No</LEDGERFROMITEM>
       <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
       <ISPARTYLEDGER>No</ISPARTYLEDGER>
       <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
       <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
       <AMOUNT>4500.00</AMOUNT>
       <GSTOVRDNASSESSABLEVALUE>4500.00</GSTOVRDNASSESSABLEVALUE>
       <VATEXPAMOUNT>4500.00</VATEXPAMOUNT>
       <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
       <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
       <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>
       <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
       <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
       <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
       <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
       <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
       <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
       <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
       <RATEDETAILS.LIST>
        <GSTRATEDUTYHEAD>Integrated Tax</GSTRATEDUTYHEAD>
        <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
       </RATEDETAILS.LIST>
       <RATEDETAILS.LIST>
        <GSTRATEDUTYHEAD>Central Tax</GSTRATEDUTYHEAD>
        <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
       </RATEDETAILS.LIST>
       <RATEDETAILS.LIST>
        <GSTRATEDUTYHEAD>State Tax</GSTRATEDUTYHEAD>
        <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
       </RATEDETAILS.LIST>
       <RATEDETAILS.LIST>
        <GSTRATEDUTYHEAD>Cess</GSTRATEDUTYHEAD>
        <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
       </RATEDETAILS.LIST>
       <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
       <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
       <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
       <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
       <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
       <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
       <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
       <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>
       <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
       <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
       <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
       <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
      </LEDGERENTRIES.LIST>
      <LEDGERENTRIES.LIST>
       <OLDAUDITENTRYIDS.LIST TYPE="Number">
        <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
       </OLDAUDITENTRYIDS.LIST>
       <ROUNDTYPE/>
       <LEDGERNAME>Integrated Tax (IGST)</LEDGERNAME>
       <GSTCLASS/>
       <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
       <LEDGERFROMITEM>No</LEDGERFROMITEM>
       <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
       <ISPARTYLEDGER>No</ISPARTYLEDGER>
       <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
       <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
       <AMOUNT>28728.00</AMOUNT>
       <VATEXPAMOUNT>28728.00</VATEXPAMOUNT>
       <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
       <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
       <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>
       <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
       <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
       <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
       <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
       <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
       <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
       <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
       <RATEDETAILS.LIST>       </RATEDETAILS.LIST>
       <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
       <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
       <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
       <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
       <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
       <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
       <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
       <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>
       <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
       <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
       <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
       <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
      </LEDGERENTRIES.LIST>
      @foreach($sales_data['salesorderitem'] as $sales_item)
        <ALLINVENTORYENTRIES.LIST>
         <BASICUSERDESCRIPTION.LIST TYPE="String">
          <BASICUSERDESCRIPTION>{{$sales_item['supplier_name']}}</BASICUSERDESCRIPTION>
         </BASICUSERDESCRIPTION.LIST>
         <STOCKITEMNAME>{{$sales_item['model_no']}}</STOCKITEMNAME>
         <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
         <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
         <ISAUTONEGATE>No</ISAUTONEGATE>
         <ISCUSTOMSCLEARANCE>No</ISCUSTOMSCLEARANCE>
         <ISTRACKCOMPONENT>No</ISTRACKCOMPONENT>
         <ISTRACKPRODUCTION>No</ISTRACKPRODUCTION>
         <ISPRIMARYITEM>No</ISPRIMARYITEM>
         <ISSCRAP>No</ISSCRAP>
         <RATE>{{$sales_item['unit_value']}}</RATE>
         <AMOUNT>{{$sales_item['total_value']}}</AMOUNT>
         <ACTUALQTY>{{$sales_item['actual_qty']}}</ACTUALQTY>
         <BILLEDQTY>{{$sales_item['qty']}}</BILLEDQTY>
         <BATCHALLOCATIONS.LIST>
          <GODOWNNAME>{{$sales_data['company_name']}}</GODOWNNAME>
          <BATCHNAME>Primary Batch</BATCHNAME>
          <INDENTNO/>
          <ORDERNO>{{$sales_item['id']}}</ORDERNO>
          <TRACKINGNUMBER/>
          <DYNAMICCSTISCLEARED>No</DYNAMICCSTISCLEARED>
          <AMOUNT>{{$sales_item['total_value']}}</AMOUNT>
          <ACTUALQTY>{{$sales_item['actual_qty']}}</ACTUALQTY>
          <BILLEDQTY>{{$sales_item['qty']}}</BILLEDQTY>
          <ORDERDUEDATE JD="43252" P="2-Jun-2018">2-Jun-2018</ORDERDUEDATE>
          <ADDITIONALDETAILS.LIST>        </ADDITIONALDETAILS.LIST>
          <VOUCHERCOMPONENTLIST.LIST>        </VOUCHERCOMPONENTLIST.LIST>
         </BATCHALLOCATIONS.LIST>
         <ACCOUNTINGALLOCATIONS.LIST>
          <OLDAUDITENTRYIDS.LIST TYPE="Number">
           <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
          </OLDAUDITENTRYIDS.LIST>
          <LEDGERNAME>Sales @ GST</LEDGERNAME>
          <GSTCLASS/>
          <GSTOVRDNNATURE>Interstate Sales Taxable</GSTOVRDNNATURE>
          <GSTOVRDNINELIGIBLEITC>&#4; Not Applicable</GSTOVRDNINELIGIBLEITC>
          <GSTOVRDNISREVCHARGEAPPL>&#4; Not Applicable</GSTOVRDNISREVCHARGEAPPL>
          <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
          <LEDGERFROMITEM>No</LEDGERFROMITEM>
          <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
          <ISPARTYLEDGER>No</ISPARTYLEDGER>
          <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
          <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
          <AMOUNT>96600.00</AMOUNT>
          <GSTOVRDNASSESSABLEVALUE>96600.00</GSTOVRDNASSESSABLEVALUE>
          <SERVICETAXDETAILS.LIST>        </SERVICETAXDETAILS.LIST>
          <BANKALLOCATIONS.LIST>        </BANKALLOCATIONS.LIST>
          <BILLALLOCATIONS.LIST>        </BILLALLOCATIONS.LIST>
          <INTERESTCOLLECTION.LIST>        </INTERESTCOLLECTION.LIST>
          <OLDAUDITENTRIES.LIST>        </OLDAUDITENTRIES.LIST>
          <ACCOUNTAUDITENTRIES.LIST>        </ACCOUNTAUDITENTRIES.LIST>
          <AUDITENTRIES.LIST>        </AUDITENTRIES.LIST>
          <INPUTCRALLOCS.LIST>        </INPUTCRALLOCS.LIST>
          <DUTYHEADDETAILS.LIST>        </DUTYHEADDETAILS.LIST>
          <EXCISEDUTYHEADDETAILS.LIST>        </EXCISEDUTYHEADDETAILS.LIST>
          <RATEDETAILS.LIST>
           <GSTRATEDUTYHEAD>Integrated Tax</GSTRATEDUTYHEAD>
          </RATEDETAILS.LIST>
          <RATEDETAILS.LIST>
           <GSTRATEDUTYHEAD>Central Tax</GSTRATEDUTYHEAD>
          </RATEDETAILS.LIST>
          <RATEDETAILS.LIST>
           <GSTRATEDUTYHEAD>State Tax</GSTRATEDUTYHEAD>
          </RATEDETAILS.LIST>
          <RATEDETAILS.LIST>
           <GSTRATEDUTYHEAD>Cess</GSTRATEDUTYHEAD>
          </RATEDETAILS.LIST>
          <SUMMARYALLOCS.LIST>        </SUMMARYALLOCS.LIST>
          <STPYMTDETAILS.LIST>        </STPYMTDETAILS.LIST>
          <EXCISEPAYMENTALLOCATIONS.LIST>        </EXCISEPAYMENTALLOCATIONS.LIST>
          <TAXBILLALLOCATIONS.LIST>        </TAXBILLALLOCATIONS.LIST>
          <TAXOBJECTALLOCATIONS.LIST>        </TAXOBJECTALLOCATIONS.LIST>
          <TDSEXPENSEALLOCATIONS.LIST>        </TDSEXPENSEALLOCATIONS.LIST>
          <VATSTATUTORYDETAILS.LIST>        </VATSTATUTORYDETAILS.LIST>
          <COSTTRACKALLOCATIONS.LIST>        </COSTTRACKALLOCATIONS.LIST>
          <REFVOUCHERDETAILS.LIST>        </REFVOUCHERDETAILS.LIST>
          <INVOICEWISEDETAILS.LIST>        </INVOICEWISEDETAILS.LIST>
          <VATITCDETAILS.LIST>        </VATITCDETAILS.LIST>
          <ADVANCETAXDETAILS.LIST>        </ADVANCETAXDETAILS.LIST>
         </ACCOUNTINGALLOCATIONS.LIST>
         <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
         <SUPPLEMENTARYDUTYHEADDETAILS.LIST>       </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
         <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
         <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
         <EXCISEALLOCATIONS.LIST>       </EXCISEALLOCATIONS.LIST>
         <EXPENSEALLOCATIONS.LIST>       </EXPENSEALLOCATIONS.LIST>
        </ALLINVENTORYENTRIES.LIST>
      @endforeach
      <PAYROLLMODEOFPAYMENT.LIST>      </PAYROLLMODEOFPAYMENT.LIST>
      <ATTDRECORDS.LIST>      </ATTDRECORDS.LIST>
      <TEMPGSTRATEDETAILS.LIST>      </TEMPGSTRATEDETAILS.LIST>
     </VOUCHER>
    </TALLYMESSAGE>
    <TALLYMESSAGE xmlns:UDF="TallyUDF">
     <COMPANY>
      <REMOTECMPINFO.LIST MERGE="Yes">
       <NAME>b46bc1ff-4e17-4958-adfa-6b8b0b8dde8e</NAME>
       <REMOTECMPNAME>{{$sales_data['company_name']}}</REMOTECMPNAME>
       <REMOTECMPSTATE>{{$sales_data['state_name']}}</REMOTECMPSTATE>
      </REMOTECMPINFO.LIST>
     </COMPANY>
    </TALLYMESSAGE>
   </REQUESTDATA>
  </IMPORTDATA>
 </BODY>
</ENVELOPE>
