<ENVELOPE>
    <HEADER>
        <TALLYREQUEST>Import Data</TALLYREQUEST>
    </HEADER>
    <BODY>
        <IMPORTDATA>
        <REQUESTDESC>
            <REPORTNAME>All Masters</REPORTNAME>
            <STATICVARIABLES>
                <SVCURRENTCOMPANY>{{$company_name['company_name']}}</SVCURRENTCOMPANY>
            </STATICVARIABLES>
        </REQUESTDESC>
    <REQUESTDATA>
    @foreach($all_manufacturer_data as $data)
        <TALLYMESSAGE xmlns:UDF="TallyUDF">
         <LEDGER NAME="{{$data['supplier_name']}}" RESERVEDNAME="">
          <ADDRESS.LIST TYPE="String">
           <ADDRESS>{{$data['address']}}</ADDRESS>
           <ADDRESS>{{$data['title']}}-{{$data['pincode']}}</ADDRESS>
          </ADDRESS.LIST>
          <MAILINGNAME.LIST TYPE="String">
           <MAILINGNAME>{{$data['supplier_name']}}</MAILINGNAME>
          </MAILINGNAME.LIST>
          <OLDAUDITENTRYIDS.LIST TYPE="Number">
           <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
          </OLDAUDITENTRYIDS.LIST>
          <GUID></GUID>
          <CURRENCYNAME>₹</CURRENCYNAME>
          <STATENAME>{{$data['state_name']}}</STATENAME>
          <PINCODE>{{$data['pincode']}}</PINCODE>
          <INCOMETAXNUMBER></INCOMETAXNUMBER>
          <INTERSTATESTNUMBER></INTERSTATESTNUMBER>
          <VATTINNUMBER></VATTINNUMBER>
          <COUNTRYNAME>{{$data['country_name']}}</COUNTRYNAME>
          <EXCISERANGE></EXCISERANGE>
          <EXCISEDIVISION></EXCISEDIVISION>
          <EXCISECOMMISSIONERATE></EXCISECOMMISSIONERATE>
          <GSTREGISTRATIONTYPE>Regular</GSTREGISTRATIONTYPE>
          <PARENT>Sundry Creditors</PARENT>
          <TAXCLASSIFICATIONNAME/>
          <TAXTYPE>Others</TAXTYPE>
          <COUNTRYOFRESIDENCE>{{$data['country_name']}}</COUNTRYOFRESIDENCE>
          <GSTTYPE/>
          <APPROPRIATEFOR/>
          <PARTYGSTIN>{{$data['gst_no']}}</PARTYGSTIN>
          <GSTNATUREOFSUPPLY/>
          <SERVICECATEGORY>&#4; Not Applicable</SERVICECATEGORY>
          <EXCISELEDGERCLASSIFICATION/>
          <EXCISEDUTYTYPE/>
          <NATUREOFSALES>Domestic</NATUREOFSALES>
          <EXCISEREGNO></EXCISEREGNO>
          <EXCISENATUREOFPURCHASE>Manufacturer</EXCISENATUREOFPURCHASE>
          <LEDGERFBTCATEGORY/>
          <LEDSTATENAME>{{$data['state_name']}}</LEDSTATENAME>
          <ISBILLWISEON>Yes</ISBILLWISEON>
          <ISCOSTCENTRESON>No</ISCOSTCENTRESON>
          <ISINTERESTON>No</ISINTERESTON>
          <ALLOWINMOBILE>No</ALLOWINMOBILE>
          <ISCOSTTRACKINGON>No</ISCOSTTRACKINGON>
          <ISBENEFICIARYCODEON>No</ISBENEFICIARYCODEON>
          <ISUPDATINGTARGETID>No</ISUPDATINGTARGETID>
          <ASORIGINAL>Yes</ASORIGINAL>
          <ISCONDENSED>No</ISCONDENSED>
          <AFFECTSSTOCK>No</AFFECTSSTOCK>
          <ISRATEINCLUSIVEVAT>No</ISRATEINCLUSIVEVAT>
          <FORPAYROLL>No</FORPAYROLL>
          <ISABCENABLED>No</ISABCENABLED>
          <ISCREDITDAYSCHKON>No</ISCREDITDAYSCHKON>
          <INTERESTONBILLWISE>No</INTERESTONBILLWISE>
          <OVERRIDEINTEREST>No</OVERRIDEINTEREST>
          <OVERRIDEADVINTEREST>No</OVERRIDEADVINTEREST>
          <USEFORVAT>No</USEFORVAT>
          <IGNORETDSEXEMPT>No</IGNORETDSEXEMPT>
          <ISTCSAPPLICABLE>No</ISTCSAPPLICABLE>
          <ISTDSAPPLICABLE>No</ISTDSAPPLICABLE>
          <ISFBTAPPLICABLE>No</ISFBTAPPLICABLE>
          <ISGSTAPPLICABLE>No</ISGSTAPPLICABLE>
          <ISEXCISEAPPLICABLE>No</ISEXCISEAPPLICABLE>
          <ISTDSEXPENSE>No</ISTDSEXPENSE>
          <ISEDLIAPPLICABLE>No</ISEDLIAPPLICABLE>
          <ISRELATEDPARTY>No</ISRELATEDPARTY>
          <USEFORESIELIGIBILITY>No</USEFORESIELIGIBILITY>
          <ISINTERESTINCLLASTDAY>No</ISINTERESTINCLLASTDAY>
          <APPROPRIATETAXVALUE>No</APPROPRIATETAXVALUE>
          <ISBEHAVEASDUTY>No</ISBEHAVEASDUTY>
          <INTERESTINCLDAYOFADDITION>No</INTERESTINCLDAYOFADDITION>
          <INTERESTINCLDAYOFDEDUCTION>No</INTERESTINCLDAYOFDEDUCTION>
          <OVERRIDECREDITLIMIT>No</OVERRIDECREDITLIMIT>
          <ISAGAINSTFORMC>No</ISAGAINSTFORMC>
          <ISCHEQUEPRINTINGENABLED>No</ISCHEQUEPRINTINGENABLED>
          <ISPAYUPLOAD>No</ISPAYUPLOAD>
          <ISPAYBATCHONLYSAL>No</ISPAYBATCHONLYSAL>
          <ISBNFCODESUPPORTED>No</ISBNFCODESUPPORTED>
          <ALLOWEXPORTWITHERRORS>No</ALLOWEXPORTWITHERRORS>
          <CONSIDERPURCHASEFOREXPORT>No</CONSIDERPURCHASEFOREXPORT>
          <USEFORNOTIONALITC>No</USEFORNOTIONALITC>
          <ISECOMMOPERATOR>No</ISECOMMOPERATOR>
          <SHOWINPAYSLIP>No</SHOWINPAYSLIP>
          <USEFORGRATUITY>No</USEFORGRATUITY>
          <ISTDSPROJECTED>No</ISTDSPROJECTED>
          <FORSERVICETAX>No</FORSERVICETAX>
          <ISINPUTCREDIT>No</ISINPUTCREDIT>
          <ISEXEMPTED>No</ISEXEMPTED>
          <ISABATEMENTAPPLICABLE>No</ISABATEMENTAPPLICABLE>
          <ISSTXPARTY>No</ISSTXPARTY>
          <ISSTXNONREALIZEDTYPE>No</ISSTXNONREALIZEDTYPE>
          <ISUSEDFORCVD>No</ISUSEDFORCVD>
          <LEDBELONGSTONONTAXABLE>No</LEDBELONGSTONONTAXABLE>
          <ISEXCISEMERCHANTEXPORTER>No</ISEXCISEMERCHANTEXPORTER>
          <ISPARTYEXEMPTED>No</ISPARTYEXEMPTED>
          <ISSEZPARTY>No</ISSEZPARTY>
          <TDSDEDUCTEEISSPECIALRATE>No</TDSDEDUCTEEISSPECIALRATE>
          <ISECHEQUESUPPORTED>No</ISECHEQUESUPPORTED>
          <ISEDDSUPPORTED>No</ISEDDSUPPORTED>
          <HASECHEQUEDELIVERYMODE>No</HASECHEQUEDELIVERYMODE>
          <HASECHEQUEDELIVERYTO>No</HASECHEQUEDELIVERYTO>
          <HASECHEQUEPRINTLOCATION>No</HASECHEQUEPRINTLOCATION>
          <HASECHEQUEPAYABLELOCATION>No</HASECHEQUEPAYABLELOCATION>
          <HASECHEQUEBANKLOCATION>No</HASECHEQUEBANKLOCATION>
          <HASEDDDELIVERYMODE>No</HASEDDDELIVERYMODE>
          <HASEDDDELIVERYTO>No</HASEDDDELIVERYTO>
          <HASEDDPRINTLOCATION>No</HASEDDPRINTLOCATION>
          <HASEDDPAYABLELOCATION>No</HASEDDPAYABLELOCATION>
          <HASEDDBANKLOCATION>No</HASEDDBANKLOCATION>
          <ISEBANKINGENABLED>No</ISEBANKINGENABLED>
          <ISEXPORTFILEENCRYPTED>No</ISEXPORTFILEENCRYPTED>
          <ISBATCHENABLED>No</ISBATCHENABLED>
          <ISPRODUCTCODEBASED>No</ISPRODUCTCODEBASED>
          <HASEDDCITY>No</HASEDDCITY>
          <HASECHEQUECITY>No</HASECHEQUECITY>
          <ISFILENAMEFORMATSUPPORTED>No</ISFILENAMEFORMATSUPPORTED>
          <HASCLIENTCODE>No</HASCLIENTCODE>
          <PAYINSISBATCHAPPLICABLE>No</PAYINSISBATCHAPPLICABLE>
          <PAYINSISFILENUMAPP>No</PAYINSISFILENUMAPP>
          <ISSALARYTRANSGROUPEDFORBRS>No</ISSALARYTRANSGROUPEDFORBRS>
          <ISEBANKINGSUPPORTED>No</ISEBANKINGSUPPORTED>
          <ISSCBUAE>No</ISSCBUAE>
          <ISBANKSTATUSAPP>No</ISBANKSTATUSAPP>
          <ISSALARYGROUPED>No</ISSALARYGROUPED>
          <USEFORPURCHASETAX>No</USEFORPURCHASETAX>
          <AUDITED>No</AUDITED>
          <SORTPOSITION> </SORTPOSITION>
          <ALTERID> </ALTERID>
          <SERVICETAXDETAILS.LIST>      </SERVICETAXDETAILS.LIST>
          <LBTREGNDETAILS.LIST>      </LBTREGNDETAILS.LIST>
          <VATDETAILS.LIST>      </VATDETAILS.LIST>
          <SALESTAXCESSDETAILS.LIST>      </SALESTAXCESSDETAILS.LIST>
          <GSTDETAILS.LIST>      </GSTDETAILS.LIST>
          <LANGUAGENAME.LIST>
           <NAME.LIST TYPE="String">
            <NAME>{{$data['supplier_name']}}</NAME>
           </NAME.LIST>
           <LANGUAGEID> </LANGUAGEID>
          </LANGUAGENAME.LIST>
          <XBRLDETAIL.LIST>      </XBRLDETAIL.LIST>
          <AUDITDETAILS.LIST>      </AUDITDETAILS.LIST>
          <SCHVIDETAILS.LIST>      </SCHVIDETAILS.LIST>
          <EXCISETARIFFDETAILS.LIST>      </EXCISETARIFFDETAILS.LIST>
          <TCSCATEGORYDETAILS.LIST>      </TCSCATEGORYDETAILS.LIST>
          <TDSCATEGORYDETAILS.LIST>      </TDSCATEGORYDETAILS.LIST>
          <SLABPERIOD.LIST>      </SLABPERIOD.LIST>
          <GRATUITYPERIOD.LIST>      </GRATUITYPERIOD.LIST>
          <ADDITIONALCOMPUTATIONS.LIST>      </ADDITIONALCOMPUTATIONS.LIST>
          <EXCISEJURISDICTIONDETAILS.LIST>      </EXCISEJURISDICTIONDETAILS.LIST>
          <EXCLUDEDTAXATIONS.LIST>      </EXCLUDEDTAXATIONS.LIST>
          <BANKALLOCATIONS.LIST>      </BANKALLOCATIONS.LIST>
          <PAYMENTDETAILS.LIST>      </PAYMENTDETAILS.LIST>
          <BANKEXPORTFORMATS.LIST>      </BANKEXPORTFORMATS.LIST>
          <BILLALLOCATIONS.LIST>      </BILLALLOCATIONS.LIST>
          <INTERESTCOLLECTION.LIST>      </INTERESTCOLLECTION.LIST>
          <LEDGERCLOSINGVALUES.LIST>      </LEDGERCLOSINGVALUES.LIST>
          <LEDGERAUDITCLASS.LIST>      </LEDGERAUDITCLASS.LIST>
          <OLDAUDITENTRIES.LIST>      </OLDAUDITENTRIES.LIST>
          <TDSEXEMPTIONRULES.LIST>      </TDSEXEMPTIONRULES.LIST>
          <DEDUCTINSAMEVCHRULES.LIST>      </DEDUCTINSAMEVCHRULES.LIST>
          <LOWERDEDUCTION.LIST>      </LOWERDEDUCTION.LIST>
          <STXABATEMENTDETAILS.LIST>      </STXABATEMENTDETAILS.LIST>
          <LEDMULTIADDRESSLIST.LIST>      </LEDMULTIADDRESSLIST.LIST>
          <STXTAXDETAILS.LIST>      </STXTAXDETAILS.LIST>
          <CHEQUERANGE.LIST>      </CHEQUERANGE.LIST>
          <DEFAULTVCHCHEQUEDETAILS.LIST>      </DEFAULTVCHCHEQUEDETAILS.LIST>
          <ACCOUNTAUDITENTRIES.LIST>      </ACCOUNTAUDITENTRIES.LIST>
          <AUDITENTRIES.LIST>      </AUDITENTRIES.LIST>
          <BRSIMPORTEDINFO.LIST>      </BRSIMPORTEDINFO.LIST>
          <AUTOBRSCONFIGS.LIST>      </AUTOBRSCONFIGS.LIST>
          <BANKURENTRIES.LIST>      </BANKURENTRIES.LIST>
          <DEFAULTCHEQUEDETAILS.LIST>      </DEFAULTCHEQUEDETAILS.LIST>
          <DEFAULTOPENINGCHEQUEDETAILS.LIST>      </DEFAULTOPENINGCHEQUEDETAILS.LIST>
          <CANCELLEDPAYALLOCATIONS.LIST>      </CANCELLEDPAYALLOCATIONS.LIST>
          <ECHEQUEPRINTLOCATION.LIST>      </ECHEQUEPRINTLOCATION.LIST>
          <ECHEQUEPAYABLELOCATION.LIST>      </ECHEQUEPAYABLELOCATION.LIST>
          <EDDPRINTLOCATION.LIST>      </EDDPRINTLOCATION.LIST>
          <EDDPAYABLELOCATION.LIST>      </EDDPAYABLELOCATION.LIST>
          <AVAILABLETRANSACTIONTYPES.LIST>      </AVAILABLETRANSACTIONTYPES.LIST>
          <LEDPAYINSCONFIGS.LIST>      </LEDPAYINSCONFIGS.LIST>
          <TYPECODEDETAILS.LIST>      </TYPECODEDETAILS.LIST>
          <FIELDVALIDATIONDETAILS.LIST>      </FIELDVALIDATIONDETAILS.LIST>
          <INPUTCRALLOCS.LIST>      </INPUTCRALLOCS.LIST>
          <GSTCLASSFNIGSTRATES.LIST>      </GSTCLASSFNIGSTRATES.LIST>
          <EXTARIFFDUTYHEADDETAILS.LIST>      </EXTARIFFDUTYHEADDETAILS.LIST>
          <VOUCHERTYPEPRODUCTCODES.LIST>      </VOUCHERTYPEPRODUCTCODES.LIST>
          <UDF:VATDEALERNATURE.LIST DESC="`VATDealerNature`" ISLIST="YES" TYPE="String" INDEX="10031">
           <UDF:VATDEALERNATURE DESC="`VATDealerNature`">Registered Dealer</UDF:VATDEALERNATURE>
          </UDF:VATDEALERNATURE.LIST>
         </LEDGER>
        </TALLYMESSAGE>
        
    @endforeach
    </REQUESTDATA>
    </IMPORTDATA>
    </BODY>
</ENVELOPE>