<ENVELOPE>
 <HEADER>
  <TALLYREQUEST>Import Data</TALLYREQUEST>
 </HEADER>
 <BODY>
  <IMPORTDATA>
   <REQUESTDESC>
    <REPORTNAME>All Masters</REPORTNAME>
    <STATICVARIABLES>
     <SVCURRENTCOMPANY>{{$company_name['company_name']}}</SVCURRENTCOMPANY>
    </STATICVARIABLES>
   </REQUESTDESC>
   <REQUESTDATA>
   @foreach($all_suppliers as $supplier_data)
    <TALLYMESSAGE xmlns:UDF="TallyUDF">
     <STOCKGROUP NAME="{{$supplier_data['supplier_name']}}" RESERVEDNAME="">
      <GUID>02d48172-939d-4952-902f-ff8438bd8e9e-000037b6</GUID>
      <PARENT/>
      <COSTINGMETHOD>Avg. Cost</COSTINGMETHOD>
      <VALUATIONMETHOD>Avg. Price</VALUATIONMETHOD>
      <BASEUNITS>Nos.</BASEUNITS>
      <ADDITIONALUNITS/>
      <ISBATCHWISEON>No</ISBATCHWISEON>
      <ISPERISHABLEON>No</ISPERISHABLEON>
      <ISADDABLE>No</ISADDABLE>
      <ISUPDATINGTARGETID>No</ISUPDATINGTARGETID>
      <ASORIGINAL>Yes</ASORIGINAL>
      <IGNOREPHYSICALDIFFERENCE>No</IGNOREPHYSICALDIFFERENCE>
      <IGNORENEGATIVESTOCK>No</IGNORENEGATIVESTOCK>
      <TREATSALESASMANUFACTURED>No</TREATSALESASMANUFACTURED>
      <TREATPURCHASESASCONSUMED>No</TREATPURCHASESASCONSUMED>
      <TREATREJECTSASSCRAP>No</TREATREJECTSASSCRAP>
      <HASMFGDATE>No</HASMFGDATE>
      <ALLOWUSEOFEXPIREDITEMS>No</ALLOWUSEOFEXPIREDITEMS>
      <IGNOREBATCHES>No</IGNOREBATCHES>
      <IGNOREGODOWNS>No</IGNOREGODOWNS>
      <ALTERID> 27334</ALTERID>
      <SERVICETAXDETAILS.LIST>      </SERVICETAXDETAILS.LIST>
      <VATDETAILS.LIST>      </VATDETAILS.LIST>
      <SALESTAXCESSDETAILS.LIST>      </SALESTAXCESSDETAILS.LIST>
      <GSTDETAILS.LIST>
       <APPLICABLEFROM>20170701</APPLICABLEFROM>
       <HSNCODE>9026</HSNCODE>
       <HSNMASTERNAME/>
       <TAXABILITY>Taxable</TAXABILITY>
       <ISREVERSECHARGEAPPLICABLE>No</ISREVERSECHARGEAPPLICABLE>
       <ISNONGSTGOODS>No</ISNONGSTGOODS>
       <GSTINELIGIBLEITC>No</GSTINELIGIBLEITC>
       <INCLUDEEXPFORSLABCALC>No</INCLUDEEXPFORSLABCALC>
       <STATEWISEDETAILS.LIST>
        <STATENAME>&#4; Any</STATENAME>
        <RATEDETAILS.LIST>
         <GSTRATEDUTYHEAD>Central Tax</GSTRATEDUTYHEAD>
         <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
         <GSTRATE> 9</GSTRATE>
        </RATEDETAILS.LIST>
        <RATEDETAILS.LIST>
         <GSTRATEDUTYHEAD>State Tax</GSTRATEDUTYHEAD>
         <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
         <GSTRATE> 9</GSTRATE>
        </RATEDETAILS.LIST>
        <RATEDETAILS.LIST>
         <GSTRATEDUTYHEAD>Integrated Tax</GSTRATEDUTYHEAD>
         <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
         <GSTRATE> 18</GSTRATE>
        </RATEDETAILS.LIST>
        <RATEDETAILS.LIST>
         <GSTRATEDUTYHEAD>Cess</GSTRATEDUTYHEAD>
         <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
        </RATEDETAILS.LIST>
        <GSTSLABRATES.LIST>        </GSTSLABRATES.LIST>
       </STATEWISEDETAILS.LIST>
       <TEMPGSTDETAILSLABRATES.LIST>       </TEMPGSTDETAILSLABRATES.LIST>
      </GSTDETAILS.LIST>
      <LANGUAGENAME.LIST>
       <NAME.LIST TYPE="String">
        <NAME>{{$supplier_data['supplier_name']}}</NAME>
       </NAME.LIST>
       <LANGUAGEID> 1033</LANGUAGEID>
      </LANGUAGENAME.LIST>
      <SCHVIDETAILS.LIST>      </SCHVIDETAILS.LIST>
      <EXCISETARIFFDETAILS.LIST>      </EXCISETARIFFDETAILS.LIST>
      <TCSCATEGORYDETAILS.LIST>      </TCSCATEGORYDETAILS.LIST>
      <TDSCATEGORYDETAILS.LIST>      </TDSCATEGORYDETAILS.LIST>
      <GSTCLASSFNIGSTRATES.LIST>      </GSTCLASSFNIGSTRATES.LIST>
      <EXTARIFFDUTYHEADDETAILS.LIST>      </EXTARIFFDUTYHEADDETAILS.LIST>
      <TEMPGSTITEMSLABRATES.LIST>      </TEMPGSTITEMSLABRATES.LIST>
     </STOCKGROUP>
    </TALLYMESSAGE>
    @endforeach
   @foreach($all_products_data as $data)
    <TALLYMESSAGE xmlns:UDF="TallyUDF">
     <STOCKITEM NAME="{{$data['model_no']}}" RESERVEDNAME="">
      <OLDAUDITENTRYIDS.LIST TYPE="Number">
       <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
      </OLDAUDITENTRYIDS.LIST>
      <GUID>02d48172-939d-4952-902f-ff8438bd8e9e-00003994</GUID>
      <PARENT>{{$data['supplier_name']}}</PARENT>
      <CATEGORY/>
      <TAXCLASSIFICATIONNAME/>
      <GSTTYPEOFSUPPLY>Goods</GSTTYPEOFSUPPLY>
      <EXCISEAPPLICABILITY>&#4; Applicable</EXCISEAPPLICABILITY>
      <SALESTAXCESSAPPLICABLE/>
      <COSTINGMETHOD>Avg. Cost</COSTINGMETHOD>
      <VALUATIONMETHOD>Avg. Price</VALUATIONMETHOD>
      <BASEUNITS>Nos.</BASEUNITS>
      <ADDITIONALUNITS/>
      <EXCISEITEMCLASSIFICATION/>
      <VATBASEUNIT>Nos</VATBASEUNIT>
      <ISCOSTCENTRESON>No</ISCOSTCENTRESON>
      <ISBATCHWISEON>No</ISBATCHWISEON>
      <ISPERISHABLEON>No</ISPERISHABLEON>
      <ISENTRYTAXAPPLICABLE>No</ISENTRYTAXAPPLICABLE>
      <ISCOSTTRACKINGON>No</ISCOSTTRACKINGON>
      <ISUPDATINGTARGETID>No</ISUPDATINGTARGETID>
      <ASORIGINAL>Yes</ASORIGINAL>
      <ISRATEINCLUSIVEVAT>No</ISRATEINCLUSIVEVAT>
      <IGNOREPHYSICALDIFFERENCE>No</IGNOREPHYSICALDIFFERENCE>
      <IGNORENEGATIVESTOCK>No</IGNORENEGATIVESTOCK>
      <TREATSALESASMANUFACTURED>No</TREATSALESASMANUFACTURED>
      <TREATPURCHASESASCONSUMED>No</TREATPURCHASESASCONSUMED>
      <TREATREJECTSASSCRAP>No</TREATREJECTSASSCRAP>
      <HASMFGDATE>No</HASMFGDATE>
      <ALLOWUSEOFEXPIREDITEMS>No</ALLOWUSEOFEXPIREDITEMS>
      <IGNOREBATCHES>No</IGNOREBATCHES>
      <IGNOREGODOWNS>No</IGNOREGODOWNS>
      <CALCONMRP>No</CALCONMRP>
      <EXCLUDEJRNLFORVALUATION>No</EXCLUDEJRNLFORVALUATION>
      <ISMRPINCLOFTAX>No</ISMRPINCLOFTAX>
      <ISADDLTAXEXEMPT>No</ISADDLTAXEXEMPT>
      <ISSUPPLEMENTRYDUTYON>No</ISSUPPLEMENTRYDUTYON>
      <GVATISEXCISEAPPL>No</GVATISEXCISEAPPL>
      <REORDERASHIGHER>No</REORDERASHIGHER>
      <MINORDERASHIGHER>No</MINORDERASHIGHER>
      <ISEXCISECALCULATEONMRP>No</ISEXCISECALCULATEONMRP>
      <INCLUSIVETAX>No</INCLUSIVETAX>
      <GSTCALCSLABONMRP>No</GSTCALCSLABONMRP>
      <MODIFYMRPRATE>No</MODIFYMRPRATE>
      <ALTERID> 31372</ALTERID>
      <DENOMINATOR> 1</DENOMINATOR>
      <RATEOFVAT>0</RATEOFVAT>
      <VATBASENO> 1</VATBASENO>
      <VATTRAILNO> 1</VATTRAILNO>
      <VATACTUALRATIO> 1</VATACTUALRATIO>
      <OPENINGBALANCE> {{$data['qty']}} Nos.</OPENINGBALANCE>
      <OPENINGVALUE>-<?= $data['price'] * $data['qty']?></OPENINGVALUE>
      <OPENINGRATE>{{$data['price']}}/Nos.</OPENINGRATE>
      <SERVICETAXDETAILS.LIST>      </SERVICETAXDETAILS.LIST>
      <VATDETAILS.LIST>      </VATDETAILS.LIST>
      <SALESTAXCESSDETAILS.LIST>      </SALESTAXCESSDETAILS.LIST>
      <GSTDETAILS.LIST>      </GSTDETAILS.LIST>
      <LANGUAGENAME.LIST>
       <NAME.LIST TYPE="String">
        <NAME>{{$data['model_no']}}</NAME>
       </NAME.LIST>
       <LANGUAGEID> 1033</LANGUAGEID>
      </LANGUAGENAME.LIST>
      <SCHVIDETAILS.LIST>      </SCHVIDETAILS.LIST>
      <EXCISETARIFFDETAILS.LIST>      </EXCISETARIFFDETAILS.LIST>
      <TCSCATEGORYDETAILS.LIST>      </TCSCATEGORYDETAILS.LIST>
      <TDSCATEGORYDETAILS.LIST>      </TDSCATEGORYDETAILS.LIST>
      <EXCLUDEDTAXATIONS.LIST>      </EXCLUDEDTAXATIONS.LIST>
      <OLDAUDITENTRIES.LIST>      </OLDAUDITENTRIES.LIST>
      <ACCOUNTAUDITENTRIES.LIST>      </ACCOUNTAUDITENTRIES.LIST>
      <AUDITENTRIES.LIST>      </AUDITENTRIES.LIST>
      <MRPDETAILS.LIST>      </MRPDETAILS.LIST>
      <VATCLASSIFICATIONDETAILS.LIST>      </VATCLASSIFICATIONDETAILS.LIST>
      <COMPONENTLIST.LIST>      </COMPONENTLIST.LIST>
      <ADDITIONALLEDGERS.LIST>      </ADDITIONALLEDGERS.LIST>
      <SALESLIST.LIST>      </SALESLIST.LIST>
      <PURCHASELIST.LIST>      </PURCHASELIST.LIST>
      <FULLPRICELIST.LIST>      </FULLPRICELIST.LIST>
      <BATCHALLOCATIONS.LIST>
       <GODOWNNAME>Main Location</GODOWNNAME>
       <BATCHNAME>Primary Batch</BATCHNAME>
       <OPENINGBALANCE> {{$data['qty']}} Nos.</OPENINGBALANCE>
       <OPENINGVALUE>-<?=$data['qty'] * $data['price']?></OPENINGVALUE>
       <OPENINGRATE>{{$data['price']}}/Nos.</OPENINGRATE>
      </BATCHALLOCATIONS.LIST>
      <TRADEREXCISEDUTIES.LIST>      </TRADEREXCISEDUTIES.LIST>
      <STANDARDCOSTLIST.LIST>      </STANDARDCOSTLIST.LIST>
      <STANDARDPRICELIST.LIST>      </STANDARDPRICELIST.LIST>
      <EXCISEITEMGODOWN.LIST>      </EXCISEITEMGODOWN.LIST>
      <MULTICOMPONENTLIST.LIST>      </MULTICOMPONENTLIST.LIST>
      <LBTDETAILS.LIST>      </LBTDETAILS.LIST>
      <PRICELEVELLIST.LIST>      </PRICELEVELLIST.LIST>
      <GSTCLASSFNIGSTRATES.LIST>      </GSTCLASSFNIGSTRATES.LIST>
      <EXTARIFFDUTYHEADDETAILS.LIST>      </EXTARIFFDUTYHEADDETAILS.LIST>
      <TEMPGSTITEMSLABRATES.LIST>      </TEMPGSTITEMSLABRATES.LIST>
      <UDF:_UDF_788530853.LIST DESC="" ISLIST="YES" TYPE="String" INDEX="1700">
       <UDF:_UDF_788530853 DESC="">{{$data['name_description']}}</UDF:_UDF_788530853>
      </UDF:_UDF_788530853.LIST>
     </STOCKITEM>
    </TALLYMESSAGE>
    @endforeach
   </REQUESTDATA>
  </IMPORTDATA>
 </BODY>
</ENVELOPE>